#!/home/dotcloud/env/bin/python
import os,sys
project = 'childapp'

# Needed to load the lincoln-style structure properly
os.system('pip install -r /home/dotcloud/code/requirements.pip')
os.system('pip install -e /home/dotcloud/code/')
sys.path.append('/home/dotcloud/code/')

# To import anything under django.*, we must set this variable.
os.environ['DJANGO_SETTINGS_MODULE'] = '%s.conf.settings' % project

# Import the admin module. The media directory is right under it!
import django.contrib.admin
# Retrieve the absolute path of the admin module.
admindir = os.path.dirname(django.contrib.admin.__file__)
# Add /media behind it.
mediadir = os.path.join(admindir, 'media')
# Compute the path of the symlink under the static directory.
staticlink = os.path.join('static', 'admin_media')
# If the link already exists, delete it.
if os.path.islink(staticlink):
    os.unlink(staticlink)
# Install the correct link.
os.symlink(mediadir, staticlink)
# create another link, this time for admin
staticlink2 = os.path.join('static', 'admin')
if os.path.islink(staticlink2):
    os.unlink(staticlink2)
os.symlink(mediadir, staticlink2)

# initialize the cron
# os.system('crontab /home/dotcloud/code/crontab')

# copy dotcloud config to local
os.system('cp /home/dotcloud/code/%s/conf/dotcloud/*.py /home/dotcloud/code/%s/conf/local/' % (project,project))
os.environ['DJANGO_SETTINGS_MODULE'] = '%s.conf.local.settings' % project

# make sure directories exist
os.system('mkdir /home/dotcloud/env/var/log/')

# attempt syncdb for any new tables
os.system('/home/dotcloud/env/bin/manage.py syncdb --migrate')

uploadsdir = '/home/dotcloud/uploads/'
os.system('mkdir %s' % uploadsdir)
uploadslink = os.path.join('static','uploads')
if os.path.islink(uploadslink):
    os.unlink(uploadslink)
os.symlink(uploadsdir, uploadslink)
